### ISSUE TITLE
Bug: SqlServer  测试链接成功，但是链接的时候提示：Connection reset

### ISSUE THREAD

**Issue by almightyYantao** [chat2db/Chat2DB#240]
### Chat2DB Version

2.0.2

### Describe the bug

![image](https://github.com/chat2db/Chat2DB/assets/34707560/550d1ec2-78b3-4131-834e-07d2cc57a28a)
![image](https://github.com/chat2db/Chat2DB/assets/34707560/08c60314-3fee-4ca6-8d03-473c626e9c03)

**Comment by chenxian01** [comment]
The error screenshot seems not match the title. From your second screenshot, it seems you already connected to the datasource, otherwise you will not see the sql console. Please check if you don't have permission for one of the databases in your datasource and try the latest version. If you still have this issue in the latest version, please provide the entire log details.

**Comment by robinji0** [comment]
Close since not update for a long time.
